[manager]
show_hidden = true

[opener]
vscode = [
    { run = 'code-oss %s', orphan = true, desc = "VS Code" }
]
open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
]

[open]
rules = [
    { mime = "text/*",        use = ["edit", "vscode"] },
    { mime = "application/*", use = ["edit", "vscode"] },
    { mime = "*",             use = ["vscode", "open", "edit"] },
]
